import { IProbability } from './probability';

export const AICharacteristics = {
  Attractive: IProbability['high'],
  Beautiful: IProbability['high'],
  Cute: IProbability['low'],
  Pretty: IProbability['low'],
  Charming: IProbability['standart'],
  Alluring: IProbability['standart'],
  Appealing: IProbability['standart'],
  Fascinating: IProbability['very-low'],
  Boring: IProbability['very-low'],
  Unattractive: IProbability['very-low'],
  Ugly: IProbability['very-low'],
  Plain: IProbability['very-low'],
  Ordinary: IProbability['very-low'],
  Unremarkable: IProbability['very-low'],
  Unimpressive: IProbability['very-low'],
  Unappealing: IProbability['very-low'],
  Unfascinating: IProbability['very-low'],
  Lovely: IProbability['very-low'],
  Gorgeous: IProbability['very-low'],
  Elegant: IProbability['very-low'],
  Graceful: IProbability['very-low'],
};
