import { IProbability } from './probability';

export const AIWomenNames = {
  Sofia: IProbability['very-high'],
  Emily: IProbability.high,
  Olivia: IProbability.high,
  Ava: IProbability.standart,
  Chloe: IProbability.standart,
  Mia: IProbability.low,
  Amelia: IProbability.low,
  Ella: IProbability['very-low'],
  Isabella: IProbability['very-low'],
  Chris: IProbability['very-high'],
  Emilia: IProbability.high,
  Kate: IProbability.high,
  Alicja: IProbability.standart,
  Klara: IProbability.standart,
  Maja: IProbability.low,
  Amelka: IProbability.low,
  Eliza: IProbability['very-low'],
  Alice: IProbability['very-low'],
  Anastasia: IProbability['very-high'],
  Viktoria: IProbability.high,
  Anna: IProbability.high,
  Maria: IProbability.standart,
  Nastya: IProbability.standart,
  Ekaterina: IProbability.low,
  Veronika: IProbability.low,
  Polina: IProbability['very-low'],
  Lisa: IProbability['very-low'],
};
