import { IProbability } from './probability';

export const AIWomenLastNames = {
  Smith: IProbability['very-high'],
  Johnson: IProbability.high,
  Williams: IProbability.high,
  Jones: IProbability.standart,
  Brown: IProbability.standart,
  Miller: IProbability.low,
  Davis: IProbability.low,
  Garcia: IProbability['very-low'],
  Rodriguez: IProbability['very-low'],
  Kowalski: IProbability['very-high'],
  Wisniewski: IProbability.high,
  Kowalczyk: IProbability.high,
  Dabrowski: IProbability.standart,
  Lech: IProbability.standart,
  Zielinski: IProbability.low,
  Szymanski: IProbability.low,
  Nowak: IProbability['very-low'],
  Majewski: IProbability['very-low'],
  Jankowski: IProbability['very-high'],
  Król: IProbability.high,
  Wojcik: IProbability.high,
  Krawczyk: IProbability.standart,
  Kaczmarek: IProbability.standart,
  Piotrowski: IProbability.low,
  Grabowski: IProbability.low,
  Nowakowski: IProbability['very-low'],
  Malinowski: IProbability['very-low'],
};
